

/* Create Tables */

CREATE TABLE MEMBER
(
	MEMBER_ID BIGINT NOT NULL AUTO_INCREMENT COMMENT '会員ID : 登録会員のID',
	MEMBER_NAME VARCHAR(50) NOT NULL COMMENT '会員名称 : 会員の名称。ニックネームでも可。',
	EMAIL_ADDRESS VARCHAR(50) NOT NULL COMMENT 'Emailアドレス : 会員のEmailアドレス',
	MEMBER_ACCOUNT VARCHAR(50) NOT NULL UNIQUE COMMENT '会員アカウント : 会員レコードの識別子。',
	MEMBER_AVATAR VARCHAR(200) NOT NULL COMMENT '会員アバター : 会員のプロフィール画像',
	REGISTER_DATETIME DATETIME NOT NULL COMMENT '登録日時 : レコードの登録日時',
	UPDATE_DATETIME DATETIME NOT NULL COMMENT '更新日時 : レコードの更新日時',
	VERSION_NO BIGINT NOT NULL COMMENT 'バージョン番号 : レコードのバージョンナンバー。排他制御をするためのカラム',
	PRIMARY KEY (MEMBER_ID)
) COMMENT = '会員 : 会員情報を保持するテーブル';


CREATE TABLE MEMBER_FOLLOWING
(
	MEMBER_FOLLOWING_ID BIGINT NOT NULL AUTO_INCREMENT COMMENT '会員フォローイングID : 会員のフォロワー、フォロイーの組み合わせレコードのID',
	FOLLOWER_ID BIGINT NOT NULL COMMENT 'フォロワーID : フォローをしている会員のID',
	FOLLOWEE_ID BIGINT NOT NULL COMMENT 'フォロイーID : フォローされる会員のID',
	REGISTER_DATETIME DATETIME NOT NULL COMMENT '登録日時 : レコードの登録日時',
	UPDATE_DATETIME DATETIME NOT NULL COMMENT '更新日時 : レコードの更新日時',
	VERSION_NO BIGINT NOT NULL COMMENT 'バージョン番号 : レコードのバージョンナンバー。排他制御をするためのカラム',
	PRIMARY KEY (MEMBER_FOLLOWING_ID)
) COMMENT = '会員フォローイング';


CREATE TABLE TWEET
(
	TWEET_ID BIGINT NOT NULL AUTO_INCREMENT COMMENT 'ツイートID : ツイートID',
	MEMBER_ID BIGINT NOT NULL COMMENT '会員ID : 登録会員のID',
	TWEET_TEXT VARCHAR(140) NOT NULL COMMENT 'ツイート本文 : ツイートの本文。140文字以内で受け付ける。',
	REGISTER_DATETIME DATETIME NOT NULL COMMENT '登録日時 : レコードの登録日時',
	UPDATE_DATETIME DATETIME NOT NULL COMMENT '更新日時 : レコードの更新日時',
	VERSION_NO BIGINT NOT NULL COMMENT 'バージョン番号 : レコードのバージョンナンバー。排他制御をするためのカラム',
	PRIMARY KEY (TWEET_ID)
) COMMENT = 'ツイート';



/* Create Indexes */

CREATE INDEX IX_MEMBER_MEMBER_NAME USING BTREE ON MEMBER (MEMBER_NAME ASC);
CREATE INDEX IX_MEMBER_MEMBER_ACCOUNT USING BTREE ON MEMBER (MEMBER_ACCOUNT ASC);
CREATE INDEX IX_MEMBER_FOLLOWING_FOLLOWER_ID USING BTREE ON MEMBER_FOLLOWING (FOLLOWER_ID ASC);
CREATE INDEX IX_MEMBER_FOLLOWING_FOLLOWEE_ID USING BTREE ON MEMBER_FOLLOWING (FOLLOWEE_ID ASC);
CREATE INDEX IX_TWEET_MEMBER_ID USING BTREE ON TWEET (MEMBER_ID ASC);



/* Create Foreign Keys */

ALTER TABLE MEMBER_FOLLOWING
	ADD CONSTRAINT FK_MEMBER_FOLLOWER FOREIGN KEY (FOLLOWER_ID)
	REFERENCES MEMBER (MEMBER_ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE MEMBER_FOLLOWING
	ADD CONSTRAINT FK_MEMBER_FOLLOWEE FOREIGN KEY (FOLLOWEE_ID)
	REFERENCES MEMBER (MEMBER_ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE TWEET
	ADD CONSTRAINT FK_TWEET_MEMBER FOREIGN KEY (MEMBER_ID)
	REFERENCES MEMBER (MEMBER_ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;



